[project]
name = "fontra"
description = "A browser-based font editor"
readme = "README.md"
authors = [
    { name = "Just van Rossum", email = "justvanrossum@gmail.com" }
]
keywords = ["font", "fonts"]
license = {text = "GNU General Public License v3"}
dependencies = [
    "aiohttp>=3.8.1",
    "fonttools[ufo,unicode]>=4.17.0",
    # "watchfiles>=0.10",
    "websockets>=10.1",
]
dynamic = ["version"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Environment :: Other Environment",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: JavaScript",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Multimedia :: Graphics",
]


[project.scripts]
fontra = "fontra.__main__:main"


[project.entry-points."fontra.views"]
editor = "fontra.views.editor"


[project.entry-points."fontra.projectmanagers"]
filesystem = "fontra.filesystem.projectmanager:FileSystemProjectManagerFactory"
rcjk = "fontra.core.projectmanager_rcjk:RCJKProjectManagerFactory"


[project.entry-points."fontra.filesystem.backends"]
rcjk = "fontra.backends.rcjk_fs:RCJKBackend"
designspace = "fontra.backends.designspace:DesignspaceBackend"
ufo = "fontra.backends.designspace:UFOBackend"


[build-system]
requires = ["setuptools", "setuptools-scm[toml]"]
build-backend = "setuptools.build_meta"


[tool.setuptools.package-data]
fontra = [
    "*.html",
    "*.ico",
    "*.css",
    "*.html",
    "*.js",
    "*.svg",
    "*.woff2",
]


[tool.setuptools_scm]
write_to = "src/fontra/_version.py"


[tool.pytest.ini_options]
testpaths = [
    "test-py",
]
